local reactor = {
	config = {
		size = { 2, 4 },
		ports = {
			input = { { side = "left", fluid = "water" } },
			output = { { side = "right", fluid = "water" } },
		},
	},
	controls = {
		scram = false,
		rod_position = 100, -- 0 = fully inserted (shutdown), 100 = fully withdrawn (max power)
	},
	state = {
		core_temp = 300, -- celsius
		core_integrity = 100, -- percent
		rod_integrity = 100, -- percent
		neutron_flux = 0.0, -- 0.0 to 1.0, drives heat generation
	},
}

-- dt = delta time in seconds since last frame
-- input = { temp, pressure, flow_rate } of incoming coolant
function reactor.run(self, dt, input)
	local state = self.state
	local controls = self.controls

	-- rod_position drives neutron flux; SCRAM overrides to 0
	local target_flux = controls.scram and 0 or (controls.rod_position / 100)
	state.neutron_flux = state.neutron_flux + (target_flux - state.neutron_flux) * dt * 0.5 -- lazy lerp toward target

	-- heat generated by fission, heat removed by coolant flow
	local heat_in = state.neutron_flux * 500 -- max 500 c/s at full flux
	local cooling = input.flow_rate * (state.core_temp - input.temp) * 0.1
	state.core_temp = state.core_temp + (heat_in - cooling) * dt

	-- degradation; rods degrade faster the hotter the core is above threshold
	if state.core_temp > 600 then
		local overheat_factor = (state.core_temp - 600) / 1000
		state.rod_integrity = state.rod_integrity - overheat_factor * dt * 5
		state.rod_integrity = math.max(state.rod_integrity, 0)
	end

	-- rod integrity loss reduces control authority; lost rods cant be inserted
	if state.rod_integrity < 50 then
		controls.rod_position = math.min(
			controls.rod_position,
			state.rod_integrity * 2 -- cant withdraw past what integrity allows
		)
	end

	-- core integrity degrades after rods are compromised
	if state.rod_integrity <= 0 then
		state.core_integrity = state.core_integrity - dt * 10
		state.core_integrity = math.max(state.core_integrity, 0)
	end

	-- output coolant is hotter and slightly higher pressure from heating
	local output = {
		temp = input.temp + (state.core_temp - input.temp) * 0.3,
		pressure = input.pressure + state.neutron_flux * 10,
		flow_rate = input.flow_rate, -- reactor doesnt change flow rate, pump does
	}

	return output, state
end

return reactor
